title: tara's blog # name of the site
author: Tara Roshan # name of site's author
# email: add an email?
url: https://tararoshan.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" for no subpath)
description: > # description of the site (multiple lines allowed)
  Tara Roshan's blog for communicating and learning in public.

permalink: /:slug.html

favicon: "favicon.svg"
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "cd .." # customize text for homepage link in post layout
  date_format: "%m-%d-%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
